const famousCartoonURL = [
  "https://www.loudegg.com/wp-content/uploads/2020/10/Bart-Simpson.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Beavis.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Betty-Boop.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Bugs-Bunny.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Butt-Head.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Buzz-Lightyear.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Charlie-Brown.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Daffy-Duck.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Daisy-Duck.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Donald-Duck.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Elmer-Fudd.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Eric-Cartman.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Fat-Albert.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Felix-The-Cat.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Fred-Flintstone.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Garfield.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/George-Jetson.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Goofy.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Hello-Kitty.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Homer-Simpson.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Jerry-Mouse.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Kenny-McCormick.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Mickey-Mouse.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Mighty-Mouse.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Minnie-Mouse.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Papa-Smurf.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Patrick-Star.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Peter-Griffin.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Pink-Panther.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Popeye.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Porky-Pig.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Ren.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Road-Runner.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Roger-Rabbit.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Scooby-Doo.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Shaggy-Rogers.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Shrek.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Snoopy.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/SpongeBob-SqaurePants.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Stimpy.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Sylvester-The-Cat.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Tigger.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Tom-Cat.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Tommy-Pickles.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Tweety-Bird.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Wile-E-Coyote.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Winnie-The-Pooh.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Woody-Woodpecker.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Woody.jpg",
  "https://www.loudegg.com/wp-content/uploads/2020/10/Yogi-Bear.jpg"
];
const famousCartoon = [
  "Bart Simpson",
  "Beavis",
  "Betty Boop",
  "Bugs Bunny",
  "Butt Head",
  "Buzz Lightyear",
  "Charlie Brown",
  "Daffy Duck",
  "Daisy Duck",
  "Donald Duck",
  "Elmer Fudd",
  "Eric Cartman",
  "Fat Albert",
  "Felix The Cat",
  "Fred Flintstone",
  "Garfield",
  "George Jetson",
  "Goofy",
  "Hello Kitty",
  "Homer Simpson",
  "Jerry Mouse",
  "Kenny McCormick",
  "Mickey Mouse",
  "Mighty Mouse",
  "Minnie Mouse",
  "Papa Smurf",
  "Patrick Star",
  "Peter Griffin",
  "Pink Panther",
  "Popeye",
  "Porky Pig",
  "Ren",
  "Road Runner",
  "Roger Rabbit",
  "Scooby Doo",
  "Shaggy Rogers",
  "Shrek",
  "Snoopy",
  "SpongeBob SqaurePants",
  "Stimpy",
  "Sylvester The Cat",
  "Tigger",
  "Tom Cat",
  "Tommy Pickles",
  "Tweety Bird",
  "Wile E Coyote",
  "Winnie The Pooh",
  "Woody Woodpecker",
  "Woody",
  "Yogi Bear"
];
