const wikimediaPeople = [
  "Taylor Swift",
  "Billie Eilish",
  "Olivia Rodrigo",
  "Ariana Grande",
  "Selena Gomez",
  "Zendaya",
  "Jenna Ortega",
  "Millie Bobby Brown",
  "Emma Watson",
  "Tom Holland",
  "Timoth\u00e9e Chalamet",
  "Florence Pugh",
  "Saoirse Ronan",
  "Anya Taylor-Joy",
  "Margot Robbie",
  "Ryan Gosling",
  "Brad Pitt",
  "Angelina Jolie",
  "Scarlett Johansson",
  "Chris Hemsworth",
  "Robert Downey Jr.",
  "Mark Ruffalo",
  "Benedict Cumberbatch",
  "Tom Hiddleston",
  "Daniel Radcliffe",
  "Rupert Grint",
  "Natalie Portman",
  "Keira Knightley",
  "Gal Gadot",
  "Jason Momoa",
  "Henry Cavill",
  "Ben Affleck",
  "Matt Damon",
  "Leonardo DiCaprio",
  "Kate Winslet",
  "Christian Bale",
  "Hugh Jackman",
  "Michael B. Jordan",
  "Denzel Washington",
  "Samuel L. Jackson",
  "Morgan Freeman",
  "Will Smith",
  "Viola Davis",
  "Jamie Foxx",
  "Kevin Hart",
  "Trevor Noah",
  "Stephen Colbert",
  "Jimmy Fallon",
  "Oprah Winfrey",
  "Gordon Ramsay",
  "Guy Fieri",
  "Padma Lakshmi",
  "Nigella Lawson",
  "Wolfgang Puck",
  "Anthony Bourdain",
  "Ryan Seacrest",
  "Simon Cowell",
  "Heidi Klum",
  "Tyra Banks",
  "Naomi Campbell",
  "Cindy Crawford",
  "Gigi Hadid",
  "Bella Hadid",
  "Kendall Jenner",
  "Kylie Jenner",
  "Kim Kardashian",
  "Hailey Bieber",
  "Justin Bieber",
  "Shawn Mendes",
  "Camila Cabello",
  "Charlie Puth",
  "Dua Lipa",
  "Rihanna",
  "Beyonc\u00e9",
  "Jay-Z",
  "The Weeknd",
  "Harry Styles",
  "Ed Sheeran",
  "Bruno Mars",
  "Lady Gaga",
  "Katy Perry",
  "Nicki Minaj",
  "Cardi B",
  "Doja Cat",
  "Lizzo",
  "SZA",
  "Adele",
  "Shakira",
  "Jennifer Lopez",
  "Mariah Carey",
  "Alicia Keys",
  "Post Malone",
  "Lil Nas X",
  "Kanye West",
  "Travis Scott",
  "Kendrick Lamar",
  "J. Cole",
  "Eminem",
  "Snoop Dogg",
  "Ice Cube",
  "Pharrell Williams",
  "Calvin Harris",
  "David Guetta",
  "Marshmello",
  "Zedd",
  "Skrillex",
  "Alan Walker",
  "MrBeast",
  "PewDiePie",
  "Markiplier",
  "Jacksepticeye",
  "Ninja",
  "Pokimane",
  "Ludwig Ahgren",
  "xQc",
  "CoryxKenshin",
  "Dream",
  "Marques Brownlee",
  "Linus Sebastian",
  "Casey Neistat",
  "Emma Chamberlain",
  "Liza Koshy",
  "Jenna Marbles",
  "Safiya Nygaard",
  "Khaby Lame",
  "Charli D'Amelio",
  "Dixie D'Amelio",
  "Addison Rae",
  "Bella Poarch",
  "Bretman Rock",
  "James Charles",
  "Tana Mongeau",
  "JoJo Siwa",
  "Noah Beck",
  "Simone Biles",
  "Serena Williams",
  "Naomi Osaka",
  "LeBron James",
  "Kevin Durant",
  "Stephen Curry",
  "Damian Lillard",
  "Luka Don\u010di\u0107",
  "Nikola Joki\u0107",
  "Giannis Antetokounmpo",
  "Michael Jordan",
  "Shaquille O'Neal",
  "Tom Brady",
  "Patrick Mahomes",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Neymar",
  "Kylian Mbapp\u00e9",
  "Erling Haaland",
  "David Beckham",
  "Usain Bolt",
  "Michael Phelps",
  "Novak Djokovic",
  "Rafael Nadal",
  "Roger Federer",
  "Sydney Sweeney",
  "Hunter Schafer",
  "Jacob Elordi",
  "Pedro Pascal",
  "Rosario Dawson",
  "Diego Luna",
  "Oscar Isaac",
  "Salma Hayek",
  "Pen\u00e9lope Cruz",
  "Antonio Banderas",
  "Javier Bardem",
  "Cate Blanchett",
  "Nicole Kidman",
  "Hugh Grant",
  "Colin Firth",
  "Daniel Craig",
  "Idris Elba",
  "Dev Patel",
  "Riz Ahmed",
  "Awkwafina",
  "Sandra Oh",
  "Michelle Yeoh",
  "Simu Liu",
  "Henry Golding",
  "Gemma Chan",
  "Jackie Chan",
  "Jet Li",
  "Donnie Yen",
  "Keanu Reeves",
  "Winona Ryder",
  "Johnny Depp",
  "Orlando Bloom",
  "Elijah Wood",
  "Ian McKellen",
  "Harrison Ford",
  "Mark Hamill",
  "Daisy Ridley",
  "John Boyega",
  "Adam Driver",
  "Tina Fey",
  "Amy Poehler",
  "Bill Hader",
  "Andy Samberg",
  "Maya Rudolph",
  "Steve Carell",
  "Rainn Wilson",
  "John Krasinski",
  "Aubrey Plaza",
  "Chris Pratt",
  "Zoe Saldaña",
  "Dave Bautista",
  "Karen Gillan",
  "Elizabeth Olsen",
  "Paul Bettany",
  "Anthony Mackie",
  "Jennifer Aniston",
  "Courteney Cox",
  "Lisa Kudrow",
  "Matt LeBlanc",
  "David Schwimmer",
  "Bryan Cranston",
  "Aaron Paul",
  "Bob Odenkirk",
  "Anna Gunn",
  "Rhea Seehorn",
  "Quinta Brunson",
  "Donald Glover",
  "Zazie Beetz",
  "Michael Shannon",
  "Albert Einstein",
  "Isaac Newton",
  "Nikola Tesla",
  "Thomas Edison",
  "Marie Curie",
  "Charles Darwin",
  "Stephen Hawking",
  "Neil Armstrong",
  "Buzz Aldrin",
  "Yuri Gagarin",
  "Amelia Earhart",
  "Martin Luther King Jr.",
  "Nelson Mandela",
  "Mahatma Gandhi",
  "Winston Churchill",
  "Franklin D. Roosevelt",
  "Abraham Lincoln",
  "George Washington",
  "Julius Caesar",
  "Cleopatra",
  "Alexander the Great",
  "Plato",
  "Aristotle",
  "Socrates",
  "Leonardo da Vinci",
  "Michelangelo",
  "Vincent van Gogh",
  "Pablo Picasso",
  "Claude Monet",
  "Andy Warhol",
  "Frida Kahlo",
  "William Shakespeare",
  "Charles Dickens",
  "Mark Twain",
  "Jane Austen",
  "George Orwell",
  "Ernest Hemingway",
  "F. Scott Fitzgerald",
  "Agatha Christie",
  "Elon Musk",
  "Jeff Bezos",
  "Bill Gates",
  "Steve Jobs",
  "Mark Zuckerberg",
  "Larry Page",
  "Sergey Brin",
  "Tim Cook",
  "Satya Nadella",
  "Sundar Pichai",
  "Reed Hastings",
  "Bob Iger",
  "Oprah Winfrey",
  "Sheryl Sandberg",
  "Joe Biden",
  "Barack Obama",
  "Donald Trump",
  "Hillary Clinton",
  "Kamala Harris",
  "Angela Merkel",
  "Justin Trudeau",
  "Emmanuel Macron",
  "Vladimir Putin",
  "Volodymyr Zelenskyy",
  "Xi Jinping",
  "Narendra Modi",
  "Shinzo Abe"
];